// DB 생성
CREATE DATABASE FAMINICLE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

// 회원 테이블
CREATE TABLE FAM_MEMBER(
	MEM_NO 			INT 			NOT NULL 	PRIMARY KEY		  		AUTO_INCREMENT 
	,ID	 			VARCHAR(20)	 	NOT NULL 
	,PASS	 		VARCHAR(20)	 	NOT NULL 
	,E_MAIL		 	VARCHAR(100) 	NOT NULL  
	,MEM_PIC_PATH   VARCHAR(255)
	,NAME	 		VARCHAR(20)	 	NOT NULL
	,BIRTHDAY	 	VARCHAR(20)	 	NOT NULL 
	,TEL	 		INT		 		NOT NULL 	  
);

// 게시물 테이블
CREATE TABLE fam_pic(
	PIC_NO 		 	INT  			NOT  NULL  	PRIMARY KEY	 	  		AUTO_INCREMENT 
	,MEM_NO	 	 	INT	  			NOT  NULL  
	,TITLE	  		VARCHAR(100)  
	,PIC_DATE	 	VARCHAR(100) 	NOT NULL  
	,PIC_FILE_PATH	 VARCHAR(100)	NOT NULL
	,LAT	 	 	VARCHAR(30)	 	 
	,LNG	 	 	VARCHAR(30)	 
);

// 기념일 테이블
CREATE TABLE EVENTDAY(
EV_NO 		INT AUTO_INCREMENT 		PRIMARY KEY, 
MEM_NO 		INT 					NOT NULL, 
EV_TITLE 	VARCHAR(100) 			NOT NULL,
EV_START 	DATE 					NOT NULL,
EV_END 		DATE,
EV_TYPE 	VARCHAR(10)
);

// 가족 신청 테이블
CREATE TABLE FAM_REQUEST (
	FAMRE_NO 	 INT 				PRIMARY KEY		AUTO_INCREMENT,
	FAMRE_REQID  VARCHAR(15) 		NOT NULL,
	FAMRE_RESID  VARCHAR(15)		NOT NULL,
	FAMRE_STATUS VARCHAR(3) 		NOT NULL 		DEFAULT 'N'
);