CREATE TABLE FAM_REQUEST (
	FAMRE_NO 	 INT AUTO_INCREMENT PRIMARY KEY,
	FAMRE_REQID  VARCHAR(15) 		NOT NULL,
	FAMRE_RESID  VARCHAR(15)		NOT NULL,
	FAMRE_STATUS VARCHAR(3) 		NOT NULL DEFAULT 'N'
);